### ISSUE TITLE
bevy-0.15

### ISSUE THREAD

**Issue by Multirious** [Multirious/bevy_time_runner#5]
Todo:
- [x] Migrate to bevy-0.15 #9 
- [x] Merge #4
- [x] Resolves #2
- [x] Update nightly docrs stuff #7|
- [x] Fix unused imports #8
- [x] Update changelog
- [x] Bump version to 0.3.0
